name: scrm
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  fl_chart: ^1.1.0
  syncfusion_flutter_gauges: ^31.1.19
  camera: ^0.11.2
  gal: ^2.3.2
  image_picker: ^1.2.0
  flutter_dotenv: ^6.0.0
  http: ^1.6.0
  provider: ^6.1.5+1
  shared_preferences: ^2.2.2
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  firebase_crashlytics: ^4.3.10

dependency_overrides:
  vector_math: ^2.1.6 # Override to resolve version conflicts

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  assets:
    - .env
    - assets/
  uses-material-design: true
